name: zubo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 */3 * *'   # 北京时间 19:00

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests aiohttp

      - name: Run script
        run: |
          python zubo.py

      - name: Commit output files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add zubo_all.txt zubo_all.m3u || true
          git commit -m "更新组播源（已测速排序）" || true
          git push
