name: zubo

on:
  schedule:
    - cron: '0 11 */3 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests aiohttp

      - name: Run
        run: |
          cd $GITHUB_WORKSPACE
          python zubo.py

      - name: Commit output files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "自动更新IP与组播文件"
          git push
